// All values use simulated seconds. Clock acceleration never changes these rules.
export const BALANCE = {
  duration: 2400,
  quickDuration: 600,
  tick: 1,
  phases: [0, 0.125, 0.375, 0.625, 0.875],
  startingResources: { credits: 1800, alloy: 1100, fuel: 600 },
  startingFleet: [5, 2, 0, 0],
  startingMiner: [2, 0, 0, 0],
  homeIncome: [360, 240, 100],
  expansionIncome: [150, 55, 35],
  midIncome: [200, 90, 45],
  coreIncome: [260, 100, 55],
  ships: [
    {
      seconds: 25,
      credits: 240,
      alloy: 140,
      power: 240,
      hull: 180,
      attack: 12,
      armor: 1,
      speed: 1.12,
      role: "Fast expansion & escorts",
    },
    {
      seconds: 42,
      credits: 480,
      alloy: 280,
      power: 560,
      hull: 430,
      attack: 27,
      armor: 2,
      speed: 1,
      role: "Anti-escort screen",
    },
    {
      seconds: 75,
      credits: 1000,
      alloy: 600,
      power: 1250,
      hull: 1050,
      attack: 62,
      armor: 4,
      speed: 0.9,
      role: "Sustained line combat",
    },
    {
      seconds: 150,
      credits: 2100,
      alloy: 1300,
      power: 2700,
      hull: 2500,
      attack: 135,
      armor: 7,
      speed: 0.75,
      role: "Heavy capital assault",
    },
  ],
  queueLimit: 10,
  berths: 2,
  fleetLimit: 5,
  shipLimit: 32,
  travelSpeed: 16,
  minTravel: 20,
  fuelPerHop: 24,
  miningSeconds: 40,
  miningAlloy: 200,
  miningFuel: 65,
  captureSeconds: 20,
  retreatSeconds: 6,
  repairPerSecond: 0.012,
  combat: {
    variation: 0.12,
    aggressiveAttack: 1.22,
    aggressiveDamage: 1.18,
    defensiveAttack: 0.82,
    defensiveDamage: 0.78,
    antiEscort: 1.3,
    capitalVsSmall: 0.75,
    escalationStarts: 30,
    escalationStep: 30,
  },
  pirates: {
    fleets: [
      [3, 0, 0, 0],
      [3, 1, 0, 0],
      [4, 2, 0, 0],
    ],
    credits: 450,
    alloy: 240,
    fuel: 90,
    score: 75,
    raidInterval: 210,
  },
  guardian: { fleet: [0, 2, 3, 1], score: 400, damage: 0.1, duration: 180 },
  leviathan: {
    fleet: [0, 0, 4, 2],
    score: 650,
    damage: 0.08,
    speed: 0.1,
    duration: 180,
    moveInterval: 65,
  },
  score: { normal: 12, strategic: 20, core: 32, kill: 2, endgameMultiplier: 2 },
  domination: { fraction: 0.6, seconds: 75 },
  buffs: {
    forge: 0.08,
    relay: 0.07,
    sensors: 1,
    titanium: 0.1,
    logistics: 0.08,
    trade: 0.1,
  },
  recovery: { duration: 120, income: 0.2, build: 0.15, cooldown: 300 },
  scoutingSeconds: 90,
  botMinReaction: 9,
  botReactionJitter: 9,
  surge: { fraction: 0.25, duration: 120, alloy: 0.4 },
  guardianFraction: 0.375,
  leviathanFraction: 0.625,
  coreWarningFraction: 0.85,
} as const;
export const PHASES = ["OPENING", "EXPANSION", "WAR", "ESCALATION", "ENDGAME"];
export const STRATEGIC = {
  forge: { name: "Helios Forge", description: "+8% ship construction" },
  relay: { name: "Nexus Relay", description: "+7% fleet travel speed" },
  sensors: { name: "Deep Sensor Array", description: "+1 detection hop" },
  titanium: { name: "Titanium Belt", description: "+10% Alloy income" },
  logistics: {
    name: "Ancient Logistics Hub",
    description: "−8% movement Fuel",
  },
  trade: { name: "Trade Nexus", description: "+10% Credits income" },
};
export type Strategic = keyof typeof STRATEGIC;
export const STAR_NAMES = [
  "Yellow main-sequence",
  "Orange star",
  "Red dwarf",
  "Blue-white star",
  "Red giant",
  "White star",
  "Binary pair",
  "Flux star",
];
